gui:
  language: "en"
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --no-gitconfig --syntax-theme="gruvbox-dark" --navigate --hunk-header-style=omit --hyperlinks --true-color=always
